  version: '3.8'
  services:
    database:
      image: mysql:8.0.32
      container_name: my-mysql-container
      restart: always
      environment:
        MYSQL_DATABASE: 'socialmedia'
        MYSQL_USER: 'socialmedia_user'
        MYSQL_PASSWORD: 'socialmedia_pass'
        MYSQL_ROOT_PASSWORD: '56146708'
      ports:
        - '3306:3306'
      volumes:
        - './volumes/mysql:/var/lib/mysql'

    springboot-app:
      build:
        context: .
        dockerfile: Dockerfile
      image: my-springboot-app
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/socialmedia
        SPRING_DATASOURCE_USERNAME: socialmedia_user
        SPRING_DATASOURCE_PASSWORD: socialmedia_pass
        SERVER_PORT: 8080
      depends_on:
        - database