version: '3.8'
services:
  database:
    image: mysql:8.0.32
    container_name: my-mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'socialmedia'
      MYSQL_USER: 'socialmedia_user'
      MYSQL_PASSWORD: 'socialmedia_pass'
      MYSQL_ROOT_PASSWORD: '56146708'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: socialmedia_user
      PMA_PASSWORD: socialmedia_pass
    ports:
      - '8081:80'